# Generated by Django 2.1.7 on 2019-06-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('book_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.BookList')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommender', to='readers.Reader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
